FROM node:alpine3.19
ENV NODE_ENV=production
WORKDIR /box-universe-server
COPY ./box-universe-server/package.json ./box-universe-server/.npmrc ./
RUN pnpm install
COPY ./box-universe-server .
CMD ["pnpm", "start:prod"]